### ISSUE TITLE
결과 이미지 저장 시 연예인 사진 크기 깨지는 버그

### ISSUE THREAD

**Issue by seoltang** [SaekKkanDa/OppaManyColorTone#199]
- 결과 페이지에서 연예인 사진이 결과 이미지 저장할 때 크기가 이상해짐
![image](https://github.com/SaekKkanDa/OppaManyColorTone/assets/91963656/1d8a1ac2-37d7-4395-94d9-fc7caec25933)

**Comment by hyeongjun3** [comment]
- 모바일 환경에서만 크기가 이상해짐 
  - (설탕 맥북) mac OS + Chrome 조합에서도 이상해집니다.
- 팔레트를 클릭하여 배경색과 폰트색을 변경했을 때 결과 저장시 어떠한 방법으로 저장할지 의논 필요

**Comment by hyeongjun3** [comment]
duplicate https://github.com/SaekKkanDa/OppaManyColorTone/issues/221
